version: '3.8'

services:
  nomad:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust the ports as needed
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mypassword
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - mynetwork

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/mypassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-data:/config
      - neo4j-data:/plugins
      - neo4j-data:/logs
    networks:
      - mynetwork
    healthcheck: # Added health check for Neo4j
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "mypassword", "RETURN 1" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
networks:
  mynetwork:
    driver: bridge

volumes:
  neo4j-data: