version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/verysecret
    ports:
      - "7474:7474"  # Map Neo4js container's port 7474 to the host
      - "7687:7687"
    volumes:
      - /neo4j/data:/data
    networks:
      - mynetwork
      -
  nomad:
    image: nomad:latest
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  /neo4j/data:
