name: deploy-to-web-app
run-name: Deploy to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ARTIFACT_ID: backend
  JAR_VERSION: 0.0.1-SNAPSHOT

jobs:
  deploy_to_web_app:
    strategy:
      matrix:
        environment: [ dev ]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
       - uses: actions/checkout@v4

       - uses: actions/setup-java@v4
         with:
           distribution: 'oracle' # See 'Supported distributions' for available options
           java-version: '21'

       - name: Build with Maven
         run: mvn -B package --file pom.xml

       - name: Build with Maven
         run: az login --identity --username ${{ secrets.AZURE_CLIENT_ID }}

       - name: Azure WebApp
         uses: Azure/webapps-deploy@v3
         with:
           app-name: web-${{ matrix.environment }}-uks-nomad-01
           package: target/${{ env.ARTIFACT_ID }}-${{ env.JAR_VERSION }}.jar