name: deploy-to-web-app
run-name: Deploy to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ARTIFACT_ID: backend
  JAR_VERSION: 0.0.1-SNAPSHOT
  PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE }}

permissions:
  id-token: write

jobs:
  deploy_to_web_app:
    strategy:
      matrix:
        environment: [ dev ]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
       - uses: actions/checkout@v4

       - uses: actions/setup-java@v4
         with:
           distribution: 'oracle' # See 'Supported distributions' for available options
           java-version: '21'

       - name: Build with Maven
         run: mvn -B package --file pom.xml

       - name: List
         run: ls ${{ github.workspace }}/target/

       - name: Azure CLI Login
         uses: azure/login@v2
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ vars.AZURE_TENANT_ID }}
           subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

       - name: Azure WebApp
         uses: Azure/webapps-deploy@v2
         with:
           app-name: web-${{ matrix.environment }}-uks-nomad-01
           publish-profile: ${{ env.PUBLISH_PROFILE }}
           package: ${{ github.workspace }}/target/${{ env.ARTIFACT_ID }}-${{ env.JAR_VERSION }}.jar